backend:
  name: git-gateway
  branch: about

# publish_mode: editorial_workflow

media_folder: "src/site/assets"
public_folder: "/assets"

collections:
  - name: "home"
    label: "Home"
    create: false
    delete: false
    editor:
      preview: false
    files:
      - name: "home"
        label: "Home Page"
        file: "src/site/index.md"
        description: "Home Page"
        fields:
            - { label: "Layout", name: "layout", widget: "hidden", default: "home.hbs" }
            - { label: "Default Page", name: "defaultPage", widget: "defaultPage" }
            - { label: "Title", name: "title", widget: "string" }
            - { label: "Hide From Navigation", name: "hideFromNav", widget: "boolean", default: true }

            - label: "Hero"
              name: "hero"
              widget: "object"
              fields:
                - { label: "Tagline", name: "tagline", widget: "text" }
                - { label: "Host Description", name: "hostDescription", widget: "string" }

            - { label: "Enable Registration", name: "enableRegistration", widget: "boolean", default: false }
            - { label: "Registration Coming Soon Text", name: "registrationComingSoonText", widget: "string" }
            - { label: "Registration Button Text", name: "registrationButtonText", widget: "string" }

            - label: "Schedule and Sessions"
              name: "schedule"
              widget: "object"
              fields:
                - { label: "Header", name: "header", widget: "string" }
                - { label: "Coming Soon Text", name: "comingSoonText", widget: "text" }
                - { label: "Previous Year Schedule Text", name: "previousYearScheduleText", widget: "string" }

            - label: "About CWITA"
              name: "about"
              widget: "object"
              fields:
                - { label: "Header", name: "header", widget: "string" }
                - { label: "About Text", name: "aboutText", widget: "text" }
                - { label: "Read More Text", name: "readMoreText", widget: "string" }

            - label: "Registration"
              name: "registration"
              widget: "object"
              fields:
                - { label: "Header", name: "header", widget: "string" }
                - { label: "Scholarship Info Text", name: "scholarshipInfoText", widget: "text" }
                - { label: "Accomodation Info Text", name: "accomodationInfoText", widget: "string" }
                - { label: "Registration Prompt", name: "registrationPrompt", widget: "string" }

            - label: "Sponsors"
              name: "sponsors"
              widget: "object"
              fields:
                - { label: "Header", name: "header", widget: "string" }
                - label: "Platnium Sponsors"
                  name: "platniumSponsors"
                  widget: "list"
                  fields:
                    - { label: "Logo", name: "logo", widget: "image" }
                    - { label: "URL", name: "url", widget: "string" }
                - label: "Gold Sponsors"
                  name: "goldSponsors"
                  widget: "list"
                  fields:
                    - { label: "Logo", name: "logo", widget: "image" }
                    - { label: "URL", name: "url", widget: "string" }
                - label: "Silver Sponsors"
                  name: "silverSponsors"
                  widget: "list"
                  fields:
                    - { label: "Logo", name: "logo", widget: "image" }
                    - { label: "URL", name: "url", widget: "string" }
                - label: "Bronze Sponsors"
                  name: "bronzeSponsors"
                  widget: "list"
                  fields:
                    - { label: "Logo", name: "logo", widget: "image" }
                    - { label: "URL", name: "url", widget: "string" }
                - { label: "Sponsor Prompt", name: "sponsorPrompt", widget: "string" }

  - name: "about"
    label: "About"
    create: false
    delete: false
    editor:
      preview: false
    files:
      - name: "about"
        label: "About Page"
        file: "src/site/about.md"
        description: "About Page"
        fields:
            - { label: "Layout", name: "layout", widget: "hidden", default: "about.hbs" }
            - { label: "Default Page", name: "defaultPage", widget: "defaultPage" }
            - { label: "Title", name: "title", widget: "string" }
            - { label: "Hide From Navigation", name: "hideFromNav", widget: "boolean", default: false }
            - { label: "Discover Wisconsin Link", name: "discoverWisLink", widget: "string", default: 'https://www.cwitc.org/our-community' }
            - { label: "Page Content", name: "body", widget: "markdown" }


  - name: "settings"
    label: "Global Settings"
    create: false
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "Site Settings"
        file: "app-config.json"
        description: "General Site Settings"
        fields:
          - { label: "Site Name", name: "siteName", widget: "string" }
          - { label: "Conference Date", name: "conferenceDate", widget: "date" }
          - { label: "Conference Start Time", name: "conferenceStartTime", widget: "datetime" }
          - { label: "Conference End Time", name: "conferenceEndTime", widget: "datetime" }